### ISSUE TITLE
Description Typo

### ISSUE THREAD

**Issue by Technetium1** [chaotic-aur/pkgbuild-obs-backgroundremoval#5]
`precomopiled` should be `precompiled` https://github.com/chaotic-aur/pkgbuild-obs-backgroundremoval/blob/e4efa20c662160271dc9a7e22f9c0cb2d842db8b/.SRCINFO#L2

**Comment by PedroHLC** [comment]
Hi, can you open a PR so we keep your contribution in the commit history? (remember to change it in the `PKGBUILD` and `.SRCINFO`)

**Comment by Technetium1** [comment]
@PedroHLC Done: https://github.com/chaotic-aur/pkgbuild-obs-backgroundremoval/pull/6
